### ISSUE TITLE
Postillion is missing

### ISSUE THREAD

**Issue by rugk** [freedomofpress/securethenews#107]
English: http://www.the-postillon.com/
German: http://www.der-postillon.com

Serious news must be secure. :laughing:

**Comment by garrettr** [comment]
Sorry, this doesn't seem like an appropriate site to include on Secure the News!

**Comment by rugk** [comment]
What?  No, why? Satire news don't need to be secured…??

**Comment by garrettr** [comment]
Satire news does not fall under the purview of Secure the News.
