### ISSUE TITLE
Update "Methodology" page content

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securethenews#111]
Suggested change:

> We will publish the Secure The News source code in the near future, and look forward to working with the community to encourage news organizations to protect their readers.

to: 
> If you're interested in getting involved, the Secure The News source code is [public on GitHub](https://github.com/freedomofpress/securethenews) ([under the AGPLv3 License](https://github.com/freedomofpress/securethenews/blob/master/LICENSE)). If you don't know what to work on, we suggest taking a look at issues that are [tagged with "contributors-welcome"](https://github.com/freedomofpress/securethenews/issues?q=is%3Aissue+is%3Aopen+label%3Acontributors-welcome).

It might also make sense to reference the API somewhere, though that might be better as a top-level link.

**Comment by conorsch** [comment]
Oops! You're right, @eloquence, we never linked to the repo when we open sourced it! I'll push these changes through right away.

**Comment by conorsch** [comment]
Methodology page has been updated: https://securethe.news/methodology-and-metrics/ Thanks, @eloquence!
