### ISSUE TITLE
Upgrade to pshtt 0.2.3

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securethenews#120]
We're currently [pinning](https://github.com/freedomofpress/securethenews/blob/e000d74d1303b58a1c75a5365f4e8004c3c8c65c/ansible/roles/securethenews-deploy/tasks/main.yml#L50-L54) our installed version of pshtt to a specific [commit](https://github.com/dhs-ncats/pshtt/commit/7362a8bdabe7190a933e4c5e18561ba9d07dc561), because it contains a fix that we needed to ensure accurate results on Secure the News, and there was a while between when the fix was committed and the pshtt maintainers created a new release.

Now the pshtt maintainers have released [pshtt 0.1.6](https://pypi.python.org/pypi/pshtt/0.1.6), which includes that fix and some others as well.

Notably, pshtt 0.1.6 upgrades the SSLyze dependency to 1.x, so we will have to make sure that transition is smooth.

**Comment by conorsch** [comment]
Latest version is now 0.2.3: https://pypi.python.org/pypi/pshtt/0.2.3 And it boasts Python3 compatibility!
