### ISSUE TITLE
Update setuptools in prod (before installing sslyze)

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securethenews#121]
> Fixes #118, based on the recommendation from nabla-c0d3/sslyze#209.

A discussion started on this issue in #119 which provided a local ansible fix. This issue is specifically aimed at tracking the fix of the issue in production.

**Comment by conorsch** [comment]
We are indeed doing this now via the `django_stack_venv_base_pkgs` role var in the django role we use: https://github.com/freedomofpress/ansible-role-django
