### ISSUE TITLE
Change elpais.es to elpais.com

### ISSUE THREAD

**Issue by justintroutman** [freedomofpress/securethenews#127]
Someone pointed out in a Redmine ticket that STN is scanning EL PAÍS's elpais.es domain (no HTTPS; gets an F), which actually redirects to elpais.com (has HTTPS). Let's check into this and change it accordingly.

**Comment by trevortimm** [comment]
We can just change this in the admin interface.

**Comment by conorsch** [comment]
@trevortimm Yes, admin updates will take effect immediately, however we _also_ have an outdated record of `elpais.es,EL PAÍS` inside the `news_sites.csv` flie within this repo, which could cause a regression if not changed.

Will push through updates on both fronts and report back here.

**Comment by trevortimm** [comment]
@conorsch 👍

**Comment by conorsch** [comment]
Change is live on the prod site. The score for EL PAÍS went from **F** -> **B**!
