### ISSUE TITLE
Possibly wrong security rating for "The Indian Express"

### ISSUE THREAD

**Issue by sidtechnical** [freedomofpress/securethenews#148]
Secure the news entry for ["The Indian Express"](https://securethe.news/sites/the-indian-express) has Security Rating **D**. The only reason it received **D** instead of **F** is because it was considered to have a valid HTTPS certificate.

However, in reality it doesn't. It can be checked [here directly](http://indianexpress.com/). So, in my opinion the security rating for The Indian Express should be **F**.

Please have a look into that if it is genuine ! 

> P.S: This was an accidental found. I am not sure if there are any similar mistakes in the script while rating other sites. Also, it could be possible due to historic reasons, _i.e._  The Indian Express used to have a valid certificate, but not any more.

**Comment by vaibhavmule** [comment]
Same with [Time.com](https://securethe.news/sites/time).

**Comment by sidtechnical** [comment]
Seems like it is the same issue will all the sites which got the rating **D**.

@vaibhavmule  are we missing something? or is this a legit wrong grading?

**Comment by vaibhavmule** [comment]
Yes, if this is case, then it is issue with all sites 

I feel it is wrong grading, on the website it says, 
`Supports HTTPS and has a valid certificate.`

- it does redirect https - http
- I doubt if they have valid certificate, but visit: https://www.ssllabs.com/ssltest/analyze.html?d=www.time.com&latest

**Comment by sidtechnical** [comment]
Yes. That exactly was my thought. Let us wait for others to confirm the same.

**Comment by vaibhavmule** [comment]
This is how it checks valid https: https://github.com/dhs-ncats/pshtt/blob/86a860c3c69a71ee29969942cd74f7a29ec16ffd/pshtt/pshtt.py#L732

The grading correct, According to [grading scale](https://securethe.news/methodology-and-metrics/#grading-scale).  it says, `HTTPS available, but downgrades to HTTP` that's when **D** rating is given.
