### ISSUE TITLE
Update markdown

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securethenews#153]
From `safety`:

> -> markdown2, installed 2.3.4, affected <2.3.5, id 35760
> An issue was discovered in markdown2 (aka python-markdown2) through 2.3.5. The safe_mode feature, which is supposed to sanitize user input against XSS, is flawed and does not escape the input properly. With a crafted payload, XSS can be triggered, as demonstrated by omitting the final '>' character from an IMG tag.

CI requires us to update this to pass

**Comment by conorsch** [comment]
Working on this...
