### ISSUE TITLE
Porting It To Another Idea

### ISSUE THREAD

**Issue by ChetanArvindPatil** [freedomofpress/securethenews#171]
Hi All,

Is it as simple as following README to port this code to new service but to track HTTPS for different domain of websites?

Can anyone please suggest if this is what all it needs to be done? I am still browsing code as to where the data is fed to scan for security.

Thanks.

**Comment by kxpvcr** [comment]
You're probably looking for https://github.com/freedomofpress/securethenews/blob/master/news_sites.csv

**Comment by conorsch** [comment]
Yes, the CSV site is a great way to get started, but most practical administration is done via the web UI, once the site is running. You can create a custom CSV and sideload that via `loadsites` manage.py command.
