### ISSUE TITLE
how to manually trigger scans in prod environment?

### ISSUE THREAD

**Issue by anoop-b** [freedomofpress/securethenews#211]
There's a mention about make `dev-scan` , how do I trigger manual site scan in prod env? does it take in the data from csv file or from the list via web admin console? 

sorry I couldn't find anything in the docs about it.

**Comment by harrislapiroff** [comment]
`./manage.py scan` is the command to run a scan. `make dev-scan` is just a shortcut to `docker-compose exec django ./manage.py scan`. Hope that helps!

**Comment by harrislapiroff** [comment]
Oh and the data comes from the database (i.e., the same as the list in the web admin). The csv is used to seed the database initially.

**Comment by anoop-b** [comment]
Thank you! 
You guys are doing a great job btw. There's a real need for something like this in India.

**Comment by harrislapiroff** [comment]
Thanks! We recently added support for [regional leaderboards](https://securethe.news/blog/introducing-regional-leaderboards-secure-news/), in fact. Currently we have an [Asia leaderboard](https://securethe.news/sites/leaderboard/asia) that includes some Indian publications, but we may get more granular in the future.
