### ISSUE TITLE
Wrong link on STN blog post

### ISSUE THREAD

**Issue by nondescriptuser** [freedomofpress/securethenews#212]
The most recent STN blog post is:
https://securethe.news/blog/introducing-regional-leaderboards-secure-news/

It notes:
----------
You can find the links to the regional leaderboards at the bottom of the Secure the News homepage:
----------

The link from 'Secure the News homepage' links to https://securethe.news/blog/  I think that it was supposed to be https://securethe.news/  (The link to regional leaderboards doesn't appear at the bottom of the main blogs page, but rather the home page.)

Also, I do find it curious that only certain parts of the world appear on the Leaderboards by Region by default.  Of the ones that do appear, Oceania is included, despite a rather small number of sites.  Whereas International and Europe only appear if one clicks to 'Show More,' even though International and Europe have more content.  Would it be possible to swap so that International or Europe might appear by default, with Oceania showing up if one selects 'Show More'?

Also, for the North America section, I don't see the New York Times.  Nor do I see the Washington Post.  Why not?  (I see the New York Post, The New Yorker and Washington Times, but not the NY Times or the Washington Post.)

In addition, for North America, would it be possible to create a sub-category for major TV-based news networks, such that ABC News, CBS News, CNN, MSNBC and Fox News can be more directly juxtaposed with each other?  (Also, maybe a sub-category for major papers, including the NY Times and the Washington Post, once those publications are added.)

Thanks.

**Comment by eloquence** [comment]
Hi there,

Sorry for the delayed response, thanks for taking the time to write this up.

- Wrong link: fixed.
- Regions collapsed: I think we should just expand the full list, added a PR to do this: #223
- Missing US orgs: these were just not added to any region, just fixed that.
- Subcategory: that's a bit more complexity than I think we're willing to take on for this feature at the moment (we're keeping the taxonomy as simple as possible). 

Generally speaking, HTTPS adoption has been awesome in the US, Europe and parts of Asia; a key motivation for this feature was to give more visibility to regions where it may still be lagging (often for political reasons, as in China).

**Comment by eloquence** [comment]
The region collapse fix is deployed; resolving this issue now.
