### ISSUE TITLE
Wrong results at some places

### ISSUE THREAD

**Issue by prateekj117** [freedomofpress/securethenews#263]
[BBC](https://www.bbc.com/news) news has no valid HTTPS according to this: https://securethe.news/sites/bbc. But that is not the case. Seeing the same thing with some other news sites like [usnews](https://www.usnews.com/).

Might be a bug in [pshtt](https://github.com/cisagov/pshtt) but not sure. Will dig deeper.

**Comment by prateekj117** [comment]
@harrislapiroff @eloquence @conorsch Didn't face it in my local. `pshtt --json bbc.co.uk` returns the correct result and it is correctly displayed in the UI on local.

**Comment by eloquence** [comment]
I noticed bbc.com was configured with a path (`/news`), which may have confused `pshtt`. I removed the path, which may fix the result on the next run.

**Comment by prateekj117** [comment]
@eloquence Wrong results for [usnews](https://securethe.news/sites/us-news-world-report) as well.

**Comment by eloquence** [comment]
@prateekj117 It looks like usnews.com performs user-agent level blocking -- I can't `wget` or `curl` it either without forcing a browser-like UA. We could generally set a browser-like UA, but honestly, IMO they've kind of earned that `F` with this site behavior -- the site doesn't even load in Tor Browser or `lynx` presumably for the same reason.

**Comment by eloquence** [comment]
Closing per above.
