### ISSUE TITLE
/pledge is still available via hyperlink in About menu

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securethenews#274]
[Edit] After following the hyperlink at the bottom of https://securethe.news/about/, I'm sent to https://securethe.news/pledge, where there is a 404 (have just noticed #162).

Looks like the copy needs to be updated if we no longer support pledging!

![Screenshot_2020-09-29 Secure the News](https://user-images.githubusercontent.com/22777700/94576478-5eb64500-0243-11eb-90d5-4fe6c93a5dfe.png)

**Comment by conorsch** [comment]
Where'd you find that URL, @rocodes? We tried to excise the pledge functionality completely back in #163. Maybe we missed something.

**Comment by rocodes** [comment]
Yeah, I just edited my comment after realizing pledge had been removed--it's in the About section at the bottom, hyperlinked and mentioned: 

"We recognize that deploying HTTPS can be a long and challenging process. If you're thinking about deploying HTTPS, consider [pledging to secure your site](https://securethe.news/pledge/). This allows us to indicate your commitment to securing your site on our main Secure The News leaderboard while it's still a work in progress."

**Comment by redshiftzero** [comment]
updated during other copy updates I made today, thanks for mentioning!
https://securethe.news/about/
