### ISSUE TITLE
allow sorting by other attributes than grade

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securethenews#277]
currently one can only sort by grade, it would be useful to sort by other attributes on the leaderboard

**Comment by SaptakS** [comment]
Do we want to allow sorting on all the attributes (given that's one and only way of filtering right now for securethenews) ? @redshiftzero what are your ideas on this?

**Comment by redshiftzero** [comment]
yeah I think it would be cool to allow the user to sort by any of the fields in the header as well
