### ISSUE TITLE
Add altnews.in and thewire.in to STN 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securethenews#301]
For posterity: documenting the request to add https://altnews.in and https://thewire.in to STN (I can add once approved).

Thanks folks!

**Comment by conorsch** [comment]
Go for it, @rocodes!

**Comment by rocodes** [comment]
Added Alt News and The Wire to STN staging yesterday, and scans completed with expected results.
 
Added them to prod, and am seeing 0/100 on their site scores; also, I noticed I did not have the option to add an onion address in prod, which makes me wonder if there is an issue with the new sites form version in Wagtail prod? I'm going to file a separate issue for that just to keep things clean.

**Comment by conorsch** [comment]
Added! You can view them here:

* https://securethe.news/sites/alt-news
* https://securethe.news/sites/wired

See related discussion in #302 for an explanation of the delay. We'll work on closing out #225 in prod soon.
