### ISSUE TITLE
`null` in onion_location_header produces unexpected sort order

### ISSUE THREAD

**Issue by thisisparker** [freedomofpress/securethenews#332]
If you sort descending by "Available Over Onion Services" on https://securethe.news/sites/, a handful of sites (currently ABC.es and the Washington Post) unexpectedly appear above the sites for which onion_location_header is `true`. This appears to be because the erroneous sites have a `null` in that field. I have not investigated nor know off-hand what circumstances produce a `null` value there.

`null` should probably not be an option, or if it is, it should not sort above `true`.

**Comment by prateekj117** [comment]
@SaptakS @chigby I can have a look into it.

**Comment by prateekj117** [comment]
@eloquence May I take this up?
