### ISSUE TITLE
API

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securethenews#89]
Other developers may wish to consume Secure the New's data for their own applications. For example, the [@SecureTheNews](https://twitter.com/securethenews) Twitter bot currently scrapes and parses the JSON from `STNsiteData` embedded in the leaderboard's HTML. We should provide a convenient RESTful API instead.

**Comment by eloquence** [comment]
I would definitely be interested in consuming such an API, and may be able to help getting it done. I've never used Django or Wagtail before, though, so pointers would be appreciated. Would we want to use an existing API plugin like http://docs.wagtail.io/en/v1.9/reference/contrib/api/ as a starting point?

**Comment by garrettr** [comment]
> Would we want to use an existing API plugin like http://docs.wagtail.io/en/v1.9/reference/contrib/api/ as a starting point?

@eloquence No, because the data that is "of interest" to external consumers (list of sites being scored, the results of the automated scans, etc.) is all handled by the `sites` app, which is fairly standalone and unrelated to the Wagtail CMS.

The rough order of tasks to tackle here would be:

1. Design the API (url scheme, request/response semantics)
2. Write unit tests for the API in a new file, e.g. `sites/test_api.py`
3. Use TDD to guide you in implementing the API. At a minimum, you will need to:
    1. Wire up the URLs in `securethenews/urls.py` and `sites/urls.py`
    2. Write API views. I would suggest doing this in a new file, separate from the main web application views, e.g. `sites/api.py`.

As far as 3rd party packages go, [Django REST framework](http://www.django-rest-framework.org/) seems like it could be useful.

**Comment by eloquence** [comment]
Okay, sounds good. As far as semantics go, how about the following:

GET /api/v1/sites - return list of all sites, similar to STNsiteData array
GET /api/v1/sites/somedomain.org - returns only the JSON data for given domain, or 404

- All responses would be JSON.
- We'd use CORS to allow cross-origin requests.

Example exchange:

GET /api/v1/sites/abcnews.go.com

->

Status: 200
Content-Type: application/json

 {
     "name": "ABC News",
     "downgrades_https": false,
     "hsts_entire_domain": null,
     "hsts_preloaded": false,
     "grade": {
         "class_name": "grade-c",
         "grade": "C"
     },
     "score": 50,
     "pledge": null,
     "absolute_url": "/sites/abc-news",
     "domain": "abcnews.go.com",
     "valid_https": true,
     "hsts": false,
     "defaults_to_https": false,
     "hsts_preload_ready": false,
     "hsts_max_age": null,
     "live": true
 }

Does that sound reasonable for starters? If so, are there any fields in the above list that should not be included in the API?

I've got the dev environment up and running - will play with the Django REST module to see how far I get with it.

**Comment by garrettr** [comment]
> Does that sound reasonable for starters?

Absolutely, and go for it! Let me know if you have any questions.

**Comment by eloquence** [comment]
OK, PR is up: https://github.com/freedomofpress/securethenews/pull/109

I've tested with a fresh vagrant box & it works; PR includes new tests.

The framework gets us a lot of stuff for free, including a web view. I've also added filters + sort orders, so you can e.g., just get the most recently added sites:

`/api/v1/sites/?ordering=-added&limit=5`

or filter by a date range, or search for a specific string. These aren't tuned to the data in scans themselves; if it's useful to query scans, we might want to add an endpoint for those as well, which should be straightforward.

Adding write access would be a bit trickier but not terribly so; I don't personally have a use case for it and I suspect you don't either at this point.

In case it's of interest, once the API is up, I'll be working on integrating relevant scan data with reviews on lib.reviews. 

Look forward to your review/comments -- this was fun to hack on.

**Comment by garrettr** [comment]
Closed in #109. Thanks again for contributing, @eloquence!
